version: '3.8'

services:
  spring-boot:
    container_name: 'gamification-container'
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8080'
    ports :
      - '8080:8080'