version: '3.8'

services:
  spring-boot:
    container_name: 'gamification-container'
    environment:
      SPRING_PROFILES_ACTIVE: prod
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8080'
    ports :
      - '8080:8080'
    depends_on:
      - db
  
  # Database
  db:
    image: library/mysql:8
    restart: always
    container_name: 'gamification_db_container'
    environment:
      MYSQL_DATABASE: 'gamificationdb'
      # User so we don't have to use root
      MYSQL_USER: 'dbGamificationDev'
      MYSQL_PASSWORD: 'devpass'
      MYSQL_ROOT_PASSWORD: 'devpa$$'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      - test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      - timeout: 10s
      - retries: 10