# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test cucumber
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run app in docker
        run: ./run-app.sh
      - name: Run Specs test
        run: |
          cd gamification-specs
          mvn test
      - name: Archive jar
        uses: actions/upload-artifact@v2
        with:
          name: app jar
          path: gamification-impl/pom.xml

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image
    needs : test
    steps:
      - uses: actions/checkout@v2
      - name: Download jar from previous job
        uses: actions/download-artifact@v2
        with:
          - name: app jar
      - name: Build and push images
        run: |
          echo ${{ secrets.REGISTERY_PAT }} | docker login ghcr.io -u dev-help2000 --password-stdin
          docker build -t amt-project/gamification .
          docker tag amt-project/gamification ghcr.io/amtproject/gamification
          docker push ghcr.io/amtproject/gamification


