# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test cucumber
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with :
          path: gamification-impl/target/gamification-impl-1.0.0.jar
          key : ${{ runner.os }}-maven-${{ hashFiles('gamification-impl/pom.xml') }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run app in docker
        run: ./run-app.sh
      - name: Run Specs test
        run: |
          cd gamification-specs
          mvn test



